const WSCodes: { [key: number]: string } = {
    1000: 'WS_CLOSE_REQUESTED',
    1011: 'INTERNAL_ERROR',
    4004: 'TOKEN_INVALID',
    4010: 'SHARDING_INVALID',
    4011: 'SHARDING_REQUIRED',
    4013: 'INVALID_INTENTS',
    4014: 'DISALLOWED_INTENTS',
};

const Status = {
    READY: 0,
    CONNECTING: 1,
    RECONNECTING: 2,
    IDLE: 3,
    NEARLY: 4,
    DISCONNECTED: 5,
    WAITING_FOR_GUILDS: 6,
    IDENTIFYING: 7,
    RESUMING: 8,
};

const Events = {
    RATE_LIMIT: 'rateLimit',
    INVALID_REQUEST_WARNING: 'invalidRequestWarning',
    API_RESPONSE: 'apiResponse',
    API_REQUEST: 'apiRequest',
    CLIENT_READY: 'ready',
    APPLICATION_COMMAND_AUTOCOMPLETE_RESPONSE: 'applicationCommandAutocompleteResponse',
    APPLICATION_COMMAND_CREATE: 'applicationCommandCreate',
    APPLICATION_COMMAND_DELETE: 'applicationCommandDelete',
    APPLICATION_COMMAND_UPDATE: 'applicationCommandUpdate',
    APPLICATION_COMMAND_PERMISSIONS_UPDATE: 'applicationCommandPermissionsUpdate',
    AUTO_MODERATION_ACTION_EXECUTION: 'autoModerationActionExecution',
    AUTO_MODERATION_RULE_CREATE: 'autoModerationRuleCreate',
    AUTO_MODERATION_RULE_DELETE: 'autoModerationRuleDelete',
    AUTO_MODERATION_RULE_UPDATE: 'autoModerationRuleUpdate',
    CALL_CREATE: 'callCreate',
    CALL_DELETE: 'callDelete',
    CALL_UPDATE: 'callUpdate',
    GUILD_CREATE: 'guildCreate',
    GUILD_DELETE: 'guildDelete',
    GUILD_UPDATE: 'guildUpdate',
    GUILD_APPLICATION_COMMANDS_UPDATE: 'guildApplicationCommandUpdate',
    GUILD_UNAVAILABLE: 'guildUnavailable',
    GUILD_MEMBER_ADD: 'guildMemberAdd',
    GUILD_MEMBER_REMOVE: 'guildMemberRemove',
    GUILD_MEMBER_UPDATE: 'guildMemberUpdate',
    GUILD_MEMBER_AVAILABLE: 'guildMemberAvailable',
    GUILD_MEMBERS_CHUNK: 'guildMembersChunk',
    GUILD_MEMBER_LIST_UPDATE: 'guildMemberListUpdate',
    GUILD_INTEGRATIONS_UPDATE: 'guildIntegrationsUpdate',
    GUILD_ROLE_CREATE: 'roleCreate',
    GUILD_ROLE_DELETE: 'roleDelete',
    INVITE_CREATE: 'inviteCreate',
    INVITE_DELETE: 'inviteDelete',
    GUILD_ROLE_UPDATE: 'roleUpdate',
    GUILD_EMOJI_CREATE: 'emojiCreate',
    GUILD_EMOJI_DELETE: 'emojiDelete',
    GUILD_EMOJI_UPDATE: 'emojiUpdate',
    GUILD_BAN_ADD: 'guildBanAdd',
    GUILD_BAN_REMOVE: 'guildBanRemove',
    CHANNEL_CREATE: 'channelCreate',
    CHANNEL_DELETE: 'channelDelete',
    CHANNEL_UPDATE: 'channelUpdate',
    CHANNEL_PINS_UPDATE: 'channelPinsUpdate',
    CHANNEL_RECIPIENT_REMOVE: 'channelRecipientRemove',
    CHANNEL_RECIPIENT_ADD: 'channelRecipientAdd',
    MESSAGE_ACK: 'messageAck',
    MESSAGE_CREATE: 'messageCreate',
    MESSAGE_DELETE: 'messageDelete',
    MESSAGE_UPDATE: 'messageUpdate',
    MESSAGE_BULK_DELETE: 'messageDeleteBulk',
    MESSAGE_REACTION_ADD: 'messageReactionAdd',
    MESSAGE_REACTION_REMOVE: 'messageReactionRemove',
    MESSAGE_REACTION_REMOVE_ALL: 'messageReactionRemoveAll',
    MESSAGE_REACTION_REMOVE_EMOJI: 'messageReactionRemoveEmoji',
    THREAD_CREATE: 'threadCreate',
    THREAD_DELETE: 'threadDelete',
    THREAD_UPDATE: 'threadUpdate',
    THREAD_LIST_SYNC: 'threadListSync',
    THREAD_MEMBER_UPDATE: 'threadMemberUpdate',
    THREAD_MEMBERS_UPDATE: 'threadMembersUpdate',
    USER_UPDATE: 'userUpdate',
    USER_SETTINGS_UPDATE: 'userSettingsUpdate',
    USER_GUILD_SETTINGS_UPDATE: 'userGuildSettingsUpdate',
    PRESENCE_UPDATE: 'presenceUpdate',
    VOICE_SERVER_UPDATE: 'voiceServerUpdate',
    VOICE_STATE_UPDATE: 'voiceStateUpdate',
    TYPING_START: 'typingStart',
    WEBHOOKS_UPDATE: 'webhookUpdate',
    INTERACTION_CREATE: 'interactionCreate',
    INTERACTION_SUCCESS: 'interactionSuccess',
    INTERACTION_FAILURE: 'interactionFailure',
    INTERACTION_MODAL_CREATE: 'interactionModalCreate',
    ERROR: 'error',
    WARN: 'warn',
    DEBUG: 'debug',
    CACHE_SWEEP: 'cacheSweep',
    SHARD_DISCONNECT: 'shardDisconnect',
    SHARD_ERROR: 'shardError',
    SHARD_RECONNECTING: 'shardReconnecting',
    SHARD_READY: 'shardReady',
    SHARD_RESUME: 'shardResume',
    INVALIDATED: 'invalidated',
    RAW: 'raw',
    STAGE_INSTANCE_CREATE: 'stageInstanceCreate',
    STAGE_INSTANCE_UPDATE: 'stageInstanceUpdate',
    STAGE_INSTANCE_DELETE: 'stageInstanceDelete',
    GUILD_STICKER_CREATE: 'stickerCreate',
    GUILD_STICKER_DELETE: 'stickerDelete',
    GUILD_STICKER_UPDATE: 'stickerUpdate',
    GUILD_SCHEDULED_EVENT_CREATE: 'guildScheduledEventCreate',
    GUILD_SCHEDULED_EVENT_UPDATE: 'guildScheduledEventUpdate',
    GUILD_SCHEDULED_EVENT_DELETE: 'guildScheduledEventDelete',
    GUILD_SCHEDULED_EVENT_USER_ADD: 'guildScheduledEventUserAdd',
    GUILD_SCHEDULED_EVENT_USER_REMOVE: 'guildScheduledEventUserRemove',
    GUILD_AUDIT_LOG_ENTRY_CREATE: 'guildAuditLogEntryCreate',
    RELATIONSHIP_ADD: 'relationshipAdd',
    RELATIONSHIP_REMOVE: 'relationshipRemove',
    RELATIONSHIP_UPDATE: 'relationshipUpdate',
    UNHANDLED_PACKET: 'unhandledPacket',
    CAPTCHA_REQUIRED: 'captchaRequired',
};

const ShardEvents = {
    CLOSE: 'close',
    DESTROYED: 'destroyed',
    INVALID_SESSION: 'invalidSession',
    READY: 'ready',
    RESUMED: 'resumed',
    ALL_READY: 'allReady',
};

const WSEvents = keyMirror([
    'READY',
    'RESUMED',
    'APPLICATION_COMMAND_AUTOCOMPLETE_RESPONSE',
    'APPLICATION_COMMAND_CREATE',
    'APPLICATION_COMMAND_DELETE',
    'APPLICATION_COMMAND_UPDATE',
    'APPLICATION_COMMAND_PERMISSIONS_UPDATE',
    'AUTO_MODERATION_ACTION_EXECUTION',
    'AUTO_MODERATION_RULE_CREATE',
    'AUTO_MODERATION_RULE_DELETE',
    'AUTO_MODERATION_RULE_UPDATE',
    'GUILD_CREATE',
    'GUILD_DELETE',
    'GUILD_UPDATE',
    'INVITE_CREATE',
    'INVITE_DELETE',
    'GUILD_MEMBER_ADD',
    'GUILD_MEMBER_REMOVE',
    'GUILD_MEMBER_UPDATE',
    'GUILD_MEMBERS_CHUNK',
    'GUILD_INTEGRATIONS_UPDATE',
    'GUILD_ROLE_CREATE',
    'GUILD_ROLE_DELETE',
    'GUILD_ROLE_UPDATE',
    'GUILD_BAN_ADD',
    'GUILD_BAN_REMOVE',
    'GUILD_EMOJIS_UPDATE',
    'CHANNEL_CREATE',
    'CHANNEL_DELETE',
    'CHANNEL_UPDATE',
    'CHANNEL_PINS_UPDATE',
    'MESSAGE_CREATE',
    'MESSAGE_DELETE',
    'MESSAGE_UPDATE',
    'MESSAGE_DELETE_BULK',
    'MESSAGE_REACTION_ADD',
    'MESSAGE_REACTION_REMOVE',
    'MESSAGE_REACTION_REMOVE_ALL',
    'MESSAGE_REACTION_REMOVE_EMOJI',
    'THREAD_CREATE',
    'THREAD_UPDATE',
    'THREAD_DELETE',
    'THREAD_LIST_SYNC',
    'THREAD_MEMBER_UPDATE',
    'THREAD_MEMBERS_UPDATE',
    'USER_UPDATE',
    'PRESENCE_UPDATE',
    'TYPING_START',
    'VOICE_STATE_UPDATE',
    'VOICE_SERVER_UPDATE',
    'WEBHOOKS_UPDATE',
    'INTERACTION_CREATE',
    'STAGE_INSTANCE_CREATE',
    'STAGE_INSTANCE_UPDATE',
    'STAGE_INSTANCE_DELETE',
    'GUILD_STICKERS_UPDATE',
    'GUILD_SCHEDULED_EVENT_CREATE',
    'GUILD_SCHEDULED_EVENT_UPDATE',
    'GUILD_SCHEDULED_EVENT_DELETE',
    'GUILD_SCHEDULED_EVENT_USER_ADD',
    'GUILD_SCHEDULED_EVENT_USER_REMOVE',
    'GUILD_AUDIT_LOG_ENTRY_CREATE',
]);

function keyMirror(arr: Array<string>) {
    const tmp: {[key: string]: string} = Object.create(null);
    for (const value of arr) tmp[value] = value;
    return tmp;
}

type EnumObj = {
    [key: number | string]: string | number;
}
function createEnum(keys: Array<string>) {
    const obj: EnumObj = {};
    for (const [index, key] of keys.entries()) {
        if (key === null) continue;
        obj[key] = index;
        obj[index] = key;
    }
    return obj;
}

function Sleep(ms: number) { return new Promise(resolve => setTimeout(resolve, ms)) }

export { WSCodes, Status, Events, ShardEvents, WSEvents, Sleep }